## Linear Regression

### Part 1 - Data Preprocessing

### Importing the dataset

In [1]:
import pandas as pd
import numpy as np
#variable and this is a function for uploading the dataset
dataset = pd.read_csv('housing.csv') 

In [2]:
dataset.head() #display 5 rows of dataset

#10,000 rows
#data points collected from a combined cycle power plant over six years
#5 columns: AT ambient temp,V exhaust vacuum, AP ambient pressure, RH relative humdity, PE net hourly  electrical energy output
# independent variables: AT, V, AP and RH
# dependent variable: PE

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880             129   
1    -122.22     37.86                  21         7099            1106   
2    -122.24     37.85                  52         1467             190   
3    -122.25     37.85                  52         1274             235   
4    -122.25     37.85                  52         1627             280   

   population  households  median_income  median_house_value ocean_proximity  
0         322         126         8.3252              452600        NEAR BAY  
1        2401        1138         8.3014              358500        NEAR BAY  
2         496         177         7.2574              352100        NEAR BAY  
3         558         219         5.6431              341300        NEAR BAY  
4         565         259         3.8462              342200        NEAR BAY

In [3]:
# [rows,columns]
X= dataset.iloc[:,:-9].values
X

array([[-122.23],
       [-122.22],
       [-122.24],
       ...,
       [-121.22],
       [-121.32],
       [-121.24]])

In [4]:
y = dataset.iloc[:,-2].values
y

array([452600, 358500, 352100, ...,  92300,  84700,  89400])

### Creating the Training Set and the Test Set

In [5]:
# scikitlearn is a library
# model_selection is a module
# train_test_split is a function
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,random_state=1)

In [6]:
X_train

array([[-122.25],
       [-119.73],
       [-122.19],
       ...,
       [-118.45],
       [-116.97],
       [-122.2 ]])

In [7]:
X_test

array([[-118.18],
       [-118.19],
       [-117.25],
       ...,
       [-123.71],
       [-122.18],
       [-118.58]])

In [8]:
y_train

array([489600,  71300, 214800, ..., 500001,  91200, 126000])

In [9]:
y_test

array([360900, 291500, 131300, ...,  69800, 500001, 220200])

## Part 2 - Building and training the model

### Building the model


In [10]:
# linear_model is the module
# `LinearRegression is a class` is defining that `LinearRegression` is a class within the `linear_model` module. It indicates that `LinearRegression` is a blueprint or template for creating objects that represent linear regression models.
# Class is a pre-coded blueprint of something we want to build from which objects are created.
from sklearn.linear_model import LinearRegression
model = LinearRegression()

### Training the Model


In [11]:
# fit is a method inside LinearRegression class - they are like functions.
model.fit(X_train, y_train)


LinearRegression()

### Inference


In [12]:
y_pred = model.predict(X_test)
y_pred

array([202927.73504898, 202957.07162219, 200199.43374092, ...,
       219150.86003134, 214662.36433098, 204101.19797718])

#### Making the prediction of a single data point with AT = 15, V = 40, AP = 1000, RH = 75

In [13]:
model.predict([[-122]])


array([214134.30601329])

## Part 3: Evaluating the Model

### R-Squared

In [14]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

-0.00023651394929680158

### Adjusted R-Squared

In [15]:
k = X_test.shape[1]
n = X_test.shape[0]
adj_r2 = 1-(1-r2)*(n-1)/(n-k-1)
adj_r2

-0.00048136988906399836

# Part 4 Gui

In this part we integrate GUI to effecctively and efficiently evaluate the

In [2]:
import tkinter as tk

# Create the main window
root = tk.Tk()
root.title("Checkbox Example")
root.attributes('-fullscreen', True)  # Set the window to full screen
root.configure(bg="#e6f7ff")  # Light blue background

# Function to create text boxes for selected checkboxes
def continue_action():
    # Clear previous text boxes
    for widget in text_frame.winfo_children():
        widget.destroy()
    
    selected_options.clear()  # Clear previous selections
    for i, var in enumerate(checkbox_vars):
        if var.get() == 1:
            selected_options.append(checkbox_labels[i])
    
    # Create text boxes for selected options
    for option in selected_options:
        label = tk.Label(text_frame, text=f"Enter value for {option}:", bg="#e6f7ff", font=("Arial", 10))
        label.pack(anchor='w', padx=10, pady=2)  # Reduced padding for a compact layout
        entry = tk.Entry(text_frame, width=30)
        entry.pack(anchor='w', padx=10, pady=2)  # Reduced padding for a compact layout

# Function to minimize the window
def minimize_window():
    root.iconify()

# Function to exit the application
def exit_app():
    root.destroy()

# Create a frame for the title bar with buttons
title_frame = tk.Frame(root, bg="#e6f7ff")
title_frame.pack(side=tk.TOP, fill=tk.X)

# Create minimize and exit buttons
minimize_button = tk.Button(title_frame, text="_", command=minimize_window, bg="#ff9966", fg="white", font=("Arial", 12), relief='flat')
minimize_button.pack(side=tk.RIGHT, padx=5)

exit_button = tk.Button(title_frame, text="X", command=exit_app, bg="#ff6666", fg="white", font=("Arial", 12), relief='flat')
exit_button.pack(side=tk.RIGHT)

# Create a frame for checkboxes
frame = tk.Frame(root, bg="#e6f7ff", padx=20, pady=10)  # Adjusted padding
frame.pack(side=tk.LEFT, padx=20)  # Padded to the left of the screen

# Create a frame for text boxes
text_frame = tk.Frame(root, bg="#e6f7ff")
text_frame.pack(side=tk.LEFT, padx=20)  # Padded to the left of the screen

# List to store the checkbox variables
checkbox_vars = []
# Labels for the checkboxes
checkbox_labels = [
    "Longitude", 
    "Latitude", 
    "Housing Median Age", 
    "Total Rooms", 
    "Total Bedrooms", 
    "Population", 
    "Households",
    "Median Income"
]

# List to store selected options
selected_options = []

# Create checkboxes with the given labels
for i, label in enumerate(checkbox_labels):
    var = tk.IntVar()
    # Alternate background colors for each checkbox
    bg_color = "#cceeff" if i % 2 == 0 else "#b3e0ff"
    checkbox = tk.Checkbutton(frame, text=label, variable=var, bg=bg_color, font=("Arial", 10), anchor='w', selectcolor="#ffcccb")
    checkbox.pack(anchor='w', padx=10, pady=2)  # Reduced padding for a compact layout
    checkbox_vars.append(var)

# Create a continue button
continue_button = tk.Button(root, text="Continue", command=continue_action, bg="#66b3ff", fg="white", font=("Arial", 12), relief='raised')
continue_button.pack(side=tk.LEFT, padx=20, pady=10)  # Padded to the left of the screen

# Add a decorative label at the top and anchor it to the left
title_label = tk.Label(root, text="Linear Regression: California Housing Prices", bg="#e6f7ff", font=("Arial", 14, "bold"))
title_label.pack(anchor='w', padx=20, pady=10)  # Fixed to the left of the screen

# Start the Tkinter event loop
root.mainloop()
